name: buckpal_app
description: BuckPal - Multi-platform budget management application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Styling
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Storage & Security
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  
  # Navigation
  go_router: ^12.1.1
  
  # File handling
  file_picker: ^6.1.1
  csv: ^5.0.2
  path_provider: ^2.1.1
  
  # Charts & Visualization
  fl_chart: ^0.65.0
  
  # Date & Time
  intl: ^0.18.1
  
  # Forms & Validation
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  
  # Loading & Progress
  flutter_spinkit: ^5.2.0
  
  # Utils
  logger: ^2.0.2
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1
  
  # Linting
  flutter_lints: ^3.0.0
  
  # Testing
  mockito: ^5.4.2
  bloc_test: ^9.1.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700